#pragma once

#include <cstdint>
#include <functional>

#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"
#include "sync/config.hpp"
#include "unions.hpp"

namespace CANopen {

/** A service driven by the SYNC object, the PDO service for instance. */
class SyncListener {
   public:
    virtual ~SyncListener() = default;
    virtual void onSync(uint8_t counter, uint32_t now_us) = 0;
};

/**
 * SYNC consumer. CiA301:2011§7.2.5 (p. 62)
 * Listens on the COB-ID of object 0x1005, keeps the counter of object
 * 0x1019 and hands every SYNC to its listener and the application.
 */
class SYNC : public Service {
   public:
    explicit SYNC(ObjectDictionnary &od, SyncListener *listener = nullptr);

    void init() override;
    bool consumes(FunctionCodes functionCode) const override {
        return functionCode == FunctionCode_SYNC;
    }
    void onFrame(class Frame &frame, uint32_t now_us) override;
    void update(uint32_t) override {}
    void onNmtState(NMTStates state) override;

    /**
     * Set a callback function called on every SYNC with the counter, before
     * the listener runs. Keep it short: it runs in the receive path.
     */
    void onSync(std::function<void(unsigned)> callback);

    uint16_t cobId() const { return syncCobId; }
    uint8_t counterOverflow() const { return overflow; }

    /* Object dictionary handlers, called through the generated tables. */
    int8_t readCounterOverflow(Data &data, int32_t id,
                               SDOAbortCodes &abortCode);
    int8_t writeCounterOverflow(const Data &data, int32_t id,
                                SDOAbortCodes &abortCode);

   private:
    void loadCobId();

    ObjectDictionnary &od;
    SyncListener *listener;
    std::function<void(unsigned)> callback;
    bool enabled = false;
    uint16_t syncCobId = sync::DEFAULT_COBID;
    uint8_t overflow = sync::COUNTER_NONE;
    uint8_t counter = 0;
    int32_t overflowId = -1;
};
}  // namespace CANopen
