#pragma once

#include <cstdint>
#include <functional>

#include "enums.hpp"
#include "hal/can-transport.hpp"
#include "hal/remote-objects.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "pdo/config.hpp"
#include "pdo/pdoChannel.hpp"
#include "service.hpp"

namespace CANopen {

/**
 * PDO service: transmit PDOs on events, timers, SYNC or remote requests and
 * unpack the received ones into the object dictionary or the remote side.
 * See CiA301:2011§7.2.2 (p. 33)
 */
class PDO : public Service {
   public:
    PDO(ObjectDictionnary &od, CanTransport &transport, RemoteObjects &remote,
        uint8_t nodeId);

    void init() override;
    bool consumes(FunctionCodes functionCode) const override;
    void onFrame(class Frame &frame, uint32_t now_us) override;
    void update(uint32_t now_us) override;
    void onNmtState(NMTStates state) override;

    /**
     * React to a SYNC: send the synchronous TPDOs, unpack the synchronous
     * RPDOs received since the previous SYNC.
     * @param counter SYNC counter, 0 when the producer does not send one.
     * @param now_us Timestamp in microseconds of the SYNC reception.
     */
    void onSync(uint8_t counter, uint32_t now_us);

    /**
     * Trigger an application event on a TPDO.
     * Event-driven PDOs are sent at once if the inhibit time has elapsed,
     * synchronous acyclic ones on the next SYNC.
     * @param number TPDO number, from 0.
     */
    void transmitTPDO(unsigned number);

    /** Resolve every mapping again and push it to the remote side. */
    void reload();

    /**
     * Set a callback function called after an RPDO is received.
     * The function receives the PDO number from 1.
     */
    void onReceive(std::function<void(unsigned)> callback);

    /**
     * Set a callback function called when an RPDO event timer elapses
     * without a frame. The function receives the PDO number from 1.
     */
    void onTimeout(std::function<void(unsigned)> callback);

    PdoChannel &tpdo(unsigned number) { return tpdos[number]; }
    PdoChannel &rpdo(unsigned number) { return rpdos[number]; }

    /* Object dictionary handlers, called through the generated tables. */
    int8_t readComm(PdoDirection direction, Data &data, int32_t id,
                    SDOAbortCodes &abortCode);
    int8_t writeComm(PdoDirection direction, const Data &data, int32_t id,
                     SDOAbortCodes &abortCode);
    int8_t readMap(PdoDirection direction, Data &data, int32_t id,
                   SDOAbortCodes &abortCode);
    int8_t writeMap(PdoDirection direction, const Data &data, int32_t id,
                    SDOAbortCodes &abortCode);

   private:
    static constexpr unsigned tpdoCount() { return OD_TPDO_COUNT; }
    static constexpr unsigned rpdoCount() { return OD_RPDO_COUNT; }

    PdoChannel *channelOf(FunctionCodes functionCode);
    PdoChannel *findComm(PdoDirection direction, int32_t id);
    PdoChannel *findMap(PdoDirection direction, int32_t id);
    void applyRemap(PdoChannel &channel);
    void configureRemote(PdoChannel &channel);
    void enable();
    void disable();
    void send(PdoChannel &channel, uint32_t now_us);
    void pack(PdoChannel &channel, uint8_t *payload);
    void unpack(PdoChannel &channel, const uint8_t *payload, uint32_t now_us);
    void onTransmitRequest(PdoChannel &channel, uint32_t now_us);
    void onReceivedFrame(PdoChannel &channel, const Frame &frame,
                         uint32_t now_us);
    bool inhibited(const PdoChannel &channel, uint32_t now_us) const;
    uint32_t syncWindow_us();

    ObjectDictionnary &od;
    CanTransport &transport;
    RemoteObjects &remote;
    const uint8_t nodeId;
    PdoChannel tpdos[pdo::slots(OD_TPDO_COUNT)];
    PdoChannel rpdos[pdo::slots(OD_RPDO_COUNT)];
    NMTStates state = NMTState_Initialisation;
    bool enabled = false;
    std::function<void(unsigned)> onReceiveFunc;
    std::function<void(unsigned)> onTimeoutFunc;
};
}  // namespace CANopen
