#pragma once

#include <cstdint>

#include "enums.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "pdo/config.hpp"
#include "unions.hpp"

namespace CANopen {

enum class PdoDirection : uint8_t { Receive, Transmit };

/**
 * One PDO of either direction: its communication and mapping parameter
 * records, the mapping resolved to dictionary ids and its runtime state.
 * See CiA301:2011§7.5.2.35 to §7.5.2.38.
 */
class PdoChannel {
   public:
    PdoChannel() = default;

    /**
     * Attach the channel to its dictionary records and load their defaults.
     * @param od The object dictionary.
     * @param direction Receive (0x1400/0x1600) or Transmit (0x1800/0x1A00).
     * @param number The PDO number, from 0.
     */
    void bind(ObjectDictionnary &od, PdoDirection direction, unsigned number);

    bool ownsCommEntry(int32_t id) const;
    bool ownsMapEntry(int32_t id) const;
    int8_t readComm(Data &data, int32_t id, SDOAbortCodes &abortCode) const;
    int8_t writeComm(const Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t readMap(Data &data, int32_t id, SDOAbortCodes &abortCode) const;
    int8_t writeMap(const Data &data, int32_t id, SDOAbortCodes &abortCode);

    /** Resolve the mapping entries to dictionary ids and the frame size. */
    void remap();
    /** Tell whether a parameter write since the last remap() needs one. */
    bool takeRemapRequest();

    PdoDirection direction() const { return dir; }
    unsigned number() const { return index; }
    bool isValid() const { return pdo::isValidCobId(cobId); }
    uint16_t canId() const { return pdo::canIdOf(cobId); }
    uint8_t transmissionType() const { return transmission; }
    bool isSynchronous() const { return pdo::isSynchronousType(transmission); }
    bool isEventDriven() const { return pdo::isEventType(transmission); }
    bool supportsInhibit() const { return commEntries >= pdo::COMM_INHIBIT; }
    bool supportsEventTimer() const {
        return commEntries >= pdo::COMM_EVENT_TIMER;
    }
    uint32_t inhibitTime_us() const {
        return supportsInhibit() ? inhibit * pdo::INHIBIT_UNIT_US : 0;
    }
    uint32_t eventTimer_us() const {
        return supportsEventTimer() ? eventTimer * pdo::EVENT_TIMER_UNIT_US : 0;
    }
    uint8_t syncStart() const { return syncStartValue; }

    uint8_t mappedCount() const { return count; }
    int32_t mappedId(unsigned position) const { return ids[position]; }
    int32_t *mappedIds() { return ids; }
    uint8_t frameSize() const { return size; }

    uint32_t lastEvent_us = 0;
    bool syncFlag = false;
    bool syncStarted = false;
    uint8_t syncCounter = 0;
    bool watchTimeout = false;
    uint8_t buffer[pdo::DLC] = {0};

   private:
    Data defaultOf(int32_t id) const;
    SDOAbortCodes checkMapEntry(uint32_t entry) const;
    uint32_t mappedSize(uint8_t entries) const;

    ObjectDictionnary *od = nullptr;
    PdoDirection dir = PdoDirection::Receive;
    unsigned index = 0;
    int32_t commId = -1;
    int32_t mapId = -1;

    uint8_t commEntries = 0;
    uint32_t cobId = pdo::COBID_INVALID;
    uint8_t transmission = 0;
    uint16_t inhibit = 0;
    uint16_t eventTimer = 0;
    uint8_t syncStartValue = 0;

    uint8_t mapEntries = 0;
    uint32_t mapping[pdo::MAPPING_MAX] = {0};

    uint8_t count = 0;
    uint8_t size = 0;
    int32_t ids[pdo::MAPPING_MAX] = {0};
    bool remapRequested = false;
};
}  // namespace CANopen
