#pragma once
#include "system.hpp"

inline void emptyGetter(Data &data) {}

inline void emptySetter(const Data &data) {}

inline void getobject6040sub0(Data &data) {
    data.u16 = sys.axis->getControlword();
}
inline void setobject6040sub0(const Data &data) {
    sys.axis->setControlword(data.u16);
}

void (*remoteGetter[63])(Data &data) = {
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    &getobject6040sub0,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
    emptyGetter,
};

void (*remoteSetter[63])(const Data &data) = {
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    &setobject6040sub0,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
    emptySetter,
};