
// Autogenerated file, do not edit
#pragma once

// Objects: 0x2007:0
enum FixtureLevel {
    FIXTURE_LEVEL__LOW = 0,
    FIXTURE_LEVEL__HIGH = 1,
};

// Objects: 0x6060:0
enum OperationModes {
    OPERATION_MODE__NONE = 0,
    OPERATION_MODE__PROFILE_POSITION = 1,
};

