"""Render the generated files from a flattened configuration."""

import configparser
import io
import os
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import jinja2
import mdformat

from .. import tree
from ..phf import PHF
from .context import RenderContext

TEMPLATE_DIR = Path(__file__).parent.parent / "templates"

EDS_BAUDRATES = [10, 20, 50, 125, 250, 500, 800, 1000]
SINGLE_ENTRY_OBJECT_TYPES = ("0x07", "0x02")

REMOTE_TYPES = {
    "i16": "REMOTE_TYPE__INT16",
    "u16": "REMOTE_TYPE__UINT16",
    "i32": "REMOTE_TYPE__INT32",
    "u32": "REMOTE_TYPE__UINT32",
    "f32": "REMOTE_TYPE__FLOAT32",
}


class Renderer:
    def __init__(self, context: RenderContext, template_dir: Path = TEMPLATE_DIR):
        self.ctx = context
        self.env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(template_dir),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def _render(self, template: str, **extra) -> str:
        now = datetime.now()
        variables = {
            "objects": self.ctx.objects,
            "node_id": self.ctx.node_id,
            "nrOfRXPDO": self.ctx.nrOfRXPDO,
            "nrOfTXPDO": self.ctx.nrOfTXPDO,
            "subindex_count": self.ctx.subindex_count,
            "type_count": self.ctx.type_count,
            "mandatoryObjects": self.ctx.mandatoryObjects,
            "optionalObjects": self.ctx.optionalObjects,
            "modules": self.ctx.modules,
            "time": now.strftime("%H:%M"),
            "date": now.strftime("%Y-%m-%d"),
            "signature": now.strftime("%Y%m%d%H%M"),
            **extra,
        }
        return self.env.get_template(template).render(**variables)

    def to_hpp(self) -> str:
        return self._render("hpp.j2") + "\n"

    def to_cpp(self) -> str:
        return self._render("cpp.j2") + "\n"

    def to_remote(self) -> str:
        pairs = [
            (
                sub.index << 8 | sub.subindex,
                (sub.cpp_instance_name, sub.type_code),
            )
            for obj in self.ctx.objects
            for sub in obj.subobjects
            if sub.remote_getter
        ]
        root = tree.build_balanced_bst(sorted(pairs, key=lambda x: x[0]))
        return self._render(
            "remote.j2", tree_array=tree.bst_to_array_zero_indexed(root)
        )

    def _enums(self) -> Dict[str, dict]:
        """Enums keyed by typedef, with the (index, subindex) that use them."""
        found = []
        for obj in self.ctx.objects:
            if obj.enum:
                found.append(((obj.index, 0), obj.enum))
            else:
                for sub in obj.subobjects:
                    if sub.enum:
                        found.append(((sub.index, sub.subindex), sub.enum))

        enums: Dict[str, dict] = {}
        for location, enum in found:
            known = enums.get(enum.typedef)
            if known is None:
                enums[enum.typedef] = {"items": enum.values, "index": [location]}
            elif known["items"].keys() != enum.values.keys():
                raise ValueError(
                    f"Enum {enum.typedef} has different items in different objects: "
                    f"{list(enum.values)} vs {list(known['items'])}"
                )
            else:
                known["index"].append(location)
        return enums

    def to_enum(self) -> str:
        template = self.env.get_template("enum.j2")
        content = textwrap.dedent(
            """
            // Autogenerated file, do not edit
            #pragma once

        """
        )
        for typedef, data in self._enums().items():
            content += (
                template.render(
                    objects=data["index"],
                    subindex=0,
                    class_name=typedef,
                    items=data["items"],
                )
                + "\n\n"
            )
        return content

    def to_modes(self) -> Optional[str]:
        modes_object = self.ctx.modes_of_operation
        if modes_object is None or modes_object.enum is None:
            return None
        headers = []
        modes = []
        for item in modes_object.enum.values:
            _, right = item.split("__", 1)
            first, *rest = right.split("_")
            suffix = first.lower() + "".join(word.capitalize() for word in rest)
            mode_suffix = "".join(word.capitalize() for word in right.split("_"))
            headers.append(f"mode_{suffix}.hpp")
            modes.append((f"Mode{mode_suffix}", suffix, item))
        return self.env.get_template("modes.j2").render(headers=headers, modes=modes)

    def to_phf(self, header_file: str) -> Tuple[str, str]:
        keys = [
            (obj.index << 8) | (sub.subindex & 0xFF)
            for obj in self.ctx.objects
            for sub in obj.subobjects
        ]
        values = list(range(len(keys)))

        phf = PHF(keys, values=values, M=None, target_load=0.877, seed=43)
        candidate_B_powers = [p for p in (8, 9) if (1 << p) <= phf.M] or None
        best = phf.build_best_parallel(
            candidate_B_powers=candidate_B_powers,
            trials_per_B=phf.trials,
            max_workers=os.cpu_count(),
        )

        mapped = sum(
            1
            for k, v in zip(phf.keys, phf.values, strict=False)
            if PHF.find_py(k, best.artifacts) == (True, v)
        )
        if mapped != len(phf.keys):
            raise ValueError("Some keys did not map correctly.")

        hpp = phf.get_hpp(trial=1, namespace="phf")
        cpp = phf.get_cpp(
            trial=1,
            header_file=header_file,
            namespace="phf",
            number_format="hex16",
            cols=10,
        )
        return hpp, cpp

    def _eds_object(self, config: configparser.ConfigParser, obj, alias: bool):
        if obj.object_type not in SINGLE_ENTRY_OBJECT_TYPES:
            config[obj.index_hex] = {
                "ParameterName": obj.name,
                "ObjectType": obj.object_type,
                "SubNumber": str(obj.subNumber),
            }

        for sub in obj.subobjects:
            section = (
                f"{sub.index_hex}sub{sub.subindex:X}"
                if obj.object_type not in SINGLE_ENTRY_OBJECT_TYPES
                else sub.index_hex
            )
            config[section] = {
                "ParameterName": sub.parameter_name,
                "ObjectType": obj.object_type,
                "DataType": sub.type_value,
                "AccessType": sub.access,
                "PDOMapping": sub.pdo_mapping,
            }
            if alias:
                config[section]["Alias"] = ""
            config[section]["DefaultValue"] = str(sub.default)

    def to_eds(self) -> str:
        device = self.ctx.config.device
        info = self.ctx.config.info
        created = info.created_at or datetime.now()
        now = datetime.now()

        config = configparser.ConfigParser(allow_no_value=True)
        config.optionxform = str

        config["FileInfo"] = {
            "FileName": f"{self.ctx.file_name}.eds",
            "FileVersion": info.file_version,
            "FileRevision": info.file_revision,
            "EDSVersion": "4.0",
            "Description": info.description,
            "CreationTime": created.strftime("%H:%M"),
            "CreationDate": created.strftime("%Y-%m-%d"),
            "CreatedBy": info.created_by,
            "ModificationTime": now.strftime("%H:%M"),
            "ModificationDate": now.strftime("%Y-%m-%d"),
            "ModifiedBy": info.modified_by,
        }

        config["DeviceInfo"] = {
            "VendorName": device.vendor.name,
            "VendorNumber": str(device.vendor.number),
            "ProductName": device.product.name,
            "ProductNumber": str(device.product.number),
            "RevisionNumber": str(device.revision.to_int()),
            "OrderCode": device.order_code,
            **{
                f"Baudrate_{rate}": str(int(rate in device.baudrate))
                for rate in EDS_BAUDRATES
            },
            "SimpleBootUpMaster": str(int(device.simple_bootup_master)),
            "SimpleBootUpSlave": str(int(device.simple_bootup_slave)),
            "Granularity": str(device.granularity),
            "DynamicChannelsSupported": str(int(device.dynamic_channels_supported)),
            "CompactPDO": str(int(device.compact_pdo)),
            "GroupMessaging": str(int(device.group_messaging)),
            "NrOfRXPDO": str(self.ctx.nrOfRXPDO),
            "NrOfTXPDO": str(self.ctx.nrOfTXPDO),
            "LSS_Supported": str(int(device.lss_supported)),
        }

        mandatory = self.ctx.mandatoryObjects
        optional = self.ctx.optionalObjects

        config["MandatoryObjects"] = {
            "SupportedObjects": str(len(mandatory)),
            **{str(i + 1): f"0x{obj.index_hex}" for i, obj in enumerate(mandatory)},
        }
        for obj in mandatory:
            self._eds_object(config, obj, alias=False)

        config["OptionalObjects"] = {
            "SupportedObjects": str(len(optional)),
            **{str(i + 1): f"0x{obj.index_hex}" for i, obj in enumerate(optional)},
        }
        for obj in optional:
            self._eds_object(config, obj, alias=True)

        output = io.StringIO()
        config.write(output)
        return output.getvalue()

    def to_md(self) -> str:
        return mdformat.text(self._render("documentation.md.j2"), extensions={"tables"})

    def to_doc(self, module: str) -> str:
        text = self._render(
            "module_documentation.md.j2",
            objects=[obj for obj in self.ctx.objects if obj.module == module],
            module=module,
            description="",
        )
        return mdformat.text(text, extensions={"tables"})

    def to_sidebar(self) -> str:
        return self._render("_sidebar.md.j2")

    def module_names(self) -> List[str]:
        return self.ctx.modules
