#pragma once

#include <cstdint>

#include "hal/can-transport.hpp"
#include "hb/config.hpp"
#include "nmt/states.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"
#include "unions.hpp"

namespace CANopen {

/**
 * Error control producer. CiA301:2011§7.2.8 (p. 68)
 * Sends the boot-up message, the heartbeat at the producer time of object
 * 0x1017 and answers node guarding requests with a toggling bit.
 */
class HB : public Service {
   public:
    HB(ObjectDictionnary &od, CanTransport &transport, uint8_t nodeId);

    void init() override;
    bool consumes(FunctionCodes functionCode) const override {
        return functionCode == FunctionCode_HEARTBEAT;
    }
    void onFrame(class Frame &frame, uint32_t now_us) override;
    void update(uint32_t now_us) override;
    void onNmtState(NMTStates state) override;

    /** Producer heartbeat time in milliseconds, 0 when off. */
    uint16_t producerTime_ms() const { return period_ms; }

    /* Object dictionary handlers, called through the generated tables. */
    int8_t readProducerTime(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t writeProducerTime(const Data &data, int32_t id,
                             SDOAbortCodes &abortCode);

   private:
    void publish(NMTStates state, bool toggle, uint32_t now_us);

    ObjectDictionnary &od;
    CanTransport &transport;
    const uint8_t nodeId;
    NMTStates state = NMTState_Initialisation;
    uint16_t period_ms = 0;
    uint32_t lastPublish_us = 0;
    bool toggle = false;
    int32_t producerTimeId = -1;
};
}  // namespace CANopen
