#pragma once

#include <cstdint>

#include "hal/remote-objects.hpp"
#include "nmt/states.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"

namespace CANopen {

class Frame;

/**
 * NMT state machine of the node. CiA301:2011§7.3.2 (p. 82)
 * Commands come from the bus or from the application; every state change is
 * published to the services attached to the node.
 */
class NMT {
   public:
    NMT(ObjectDictionnary &od, RemoteObjects &remote, ServiceBus &bus,
        uint8_t nodeId);

    /** Application hook run after a reset node, once the remote side is
     * reset. */
    void (*onReset)() = nullptr;

    /**
     * Run the Initialisation state and enter Pre-Operational.
     * Called once by Node::init().
     */
    void initSM();

    /**
     * Process an NMT command frame addressed to this node or broadcast.
     * Called by Node::receiveFrame().
     */
    void receiveFrame(const Frame &frame);

    /**
     * Issue a state machine transition based on the given command.
     * Commands that CiA 301 does not allow from the current state are
     * ignored.
     */
    void setTransition(NMTServiceCommands command);

    NMTStates getState() const { return currentState; }

   private:
    void reset(uint8_t parameterGroup);
    void enter(NMTStates state);

    ObjectDictionnary &od;
    RemoteObjects &remote;
    ServiceBus &bus;
    const uint8_t nodeId;
    NMTStates currentState = NMTState_Initialisation;
};
}  // namespace CANopen
