#pragma once

#include <cstdint>

#include "emcy/codes.hpp"
#include "emcy/config.hpp"
#include "hal/can-transport.hpp"
#include "nmt/nmt.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"
#include "unions.hpp"

namespace CANopen {

/** The pre-defined error field, object 0x1003: newest error first. */
class ErrorHistory {
   public:
    void clear();
    void push(uint32_t error);
    uint8_t count() const { return size; }
    uint32_t at(unsigned position) const { return errors[position]; }

   private:
    uint8_t size = 0;
    uint32_t errors[emcy::HISTORY_SIZE] = {0};
};

/**
 * Emergency producer. CiA301:2011§7.2.7 (p. 64)
 * Keeps the error register, the error history and the error behavior, and
 * sends an emergency message on every new error and on the last error
 * cleared.
 */
class EMCY : public Service {
   public:
    EMCY(ObjectDictionnary &od, CanTransport &transport, NMT &nmt,
         uint8_t nodeId);

    void init() override;
    bool consumes(FunctionCodes) const override { return false; }
    void onFrame(class Frame &, uint32_t) override {}
    void update(uint32_t) override {}
    void onNmtState(NMTStates state) override;

    /**
     * Raise an error: set its error register bit, record it, send the
     * emergency message and apply the error behavior.
     * @param errorCode Emergency error code.
     * @param manufacturerCode Manufacturer specific code, zero if unused.
     */
    void raiseError(uint16_t errorCode, uint16_t manufacturerCode = 0);

    /**
     * Clear an error register bit. The generic bit clears itself with the
     * last specific bit; an error-free register sends an error reset.
     */
    void clearErrorBit(ErrorRegisterBits bit);

    /** Clear the error register bit that the given error code sets. */
    void clearErrorBit(EMCYErrorCodes code);

    uint8_t getErrorRegister() const { return errorRegister; }
    const ErrorHistory &history() const { return errors; }
    void clearHistory() { errors.clear(); }
    void reset() { errorRegister = 0; }

    /** Set the error behavior, object 0x1029, when the dictionary has none. */
    void setErrorBehavior(ErrorBehaviorValue onCommunicationError,
                          ErrorBehaviorValue onDeviceError);

    /* Object dictionary handlers, called through the generated tables. */
    int8_t readRegister(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t readHistory(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t writeHistory(const Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t readBehavior(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t writeBehavior(const Data &data, int32_t id,
                         SDOAbortCodes &abortCode);

   private:
    void send(uint16_t errorCode, uint32_t manufacturerCode);
    void applyBehavior(uint16_t errorCode);
    Data defaultOf(int32_t id) const;

    ObjectDictionnary &od;
    CanTransport &transport;
    NMT &nmt;
    const uint8_t nodeId;
    bool enabled = false;
    uint8_t errorRegister = 0;
    ErrorHistory errors;
    ErrorBehaviorValue communicationBehavior =
        ErrorBehaviorValue_PreOperational;
    ErrorBehaviorValue deviceBehavior = ErrorBehaviorValue_PreOperational;
    int32_t registerId = -1;
    int32_t historyId = -1;
    int32_t behaviorId = -1;
};
}  // namespace CANopen
