profiles:
- profile: 301
  name: Application layer and communication profile
  objects:
  - index: 0x1000
    name: Device type
    category: mandatory
    type : uint32
    data:
    - access: ro
      pdo_mapping: False
      default: true
  - index: 0x1001
    name: Error register
    category: mandatory
    data:
    - type: uint8
      access: ro
      pdo_mapping: true
      default: false
  - index: 0x1002
    name: Manufacturer status register
    category: optional
    data:
    - type: uint32
      access: ro
      pdo_mapping: true
      default: false
  - index: 0x1003
    name: Pre-defined error field
    category: optional
    data:
    - type: uint8
      name: Number of errors
      access: rw
      pdo_mapping: False
      default: true
      default_value: 0
    - type: uint32
      name: Standard error field
      access: ro
      pdo_mapping: False
      default: false
    - type: uint32
      name: Standard error field
      access: ro
      pdo_mapping: False
      default: false
- profile: 402
  name: Profile for drives and motion control
  objects:
  - index: 0x6040
    name: Controlword
    category: mandatory
    data:
    - type: uint16
      access: rw
      pdo_mapping: true
      default: true
  - index: 0x6041
    name: Statusword
    category: mandatory
    data:
    - type: uint16
      access: ro
      pdo_mapping: true
      default: false


      