functionalities:
  baudrate:
    10: true
    20: true
    50: true
    125: true
    250: true
    500: true
    800: true
    1000: true
  simpleBootUpMaster: false
  simpleBootUpSlave: true
  granularity: 8
  dynamicChannelsSupported: false
  compactPDO: false
  groupMessaging: false
  LSS_Supported: false


profiles:
  301:
    name: Application layer and communication profile
    objects:
      0x1000:
        name: Device type
        category: mandatory
        data:
        - type : uint32
          access: ro
      0x1001:
        name: Error register
        category: mandatory
        data:
        - type: uint8
          access: ro
          pdo_mapping: true
      0x1002:
        name: Manufacturer status register
        category: optional
        data:
        - type: uint32
          access: ro
          pdo_mapping: true
      0x1003:
        name: Pre-defined error field
        category: optional
        data:
        - type: uint8
          name: Number of errors
          access: rw
          default: 0
        - type: uint32
          name: 1st Standard error field
          access: ro
        - type: uint32
          name: 2nt Standard error field
          access: ro
        - type: uint32
          name: 3th Standard error field
          access: ro
        - type: uint32
          name: 4th Standard error field
          access: ro
        - type: uint32
          name: 5th Standard error field
          access: ro
        - type: uint32
          name: 6th Standard error field
          access: ro
        - type: uint32
          name: 7th Standard error field
          access: ro
        - type: uint32
          name: 8th Standard error field
          access: ro
      0x1007:
        name: Synchronous window length
        category: optional
        data:
        - type: uint32
          access: rw
          default: 0
      0x1008:
        name: Manufacturer device name
        category: optional
        data:
        - type: string
          access: ro
      0x1009:
        name: Manufacturer hardware version
        category: optional
        data:
        - type: string
          access: ro
      0x100A:
        name: Manufacturer software version
        category: optional
        data:
        - type: string
          access: ro
      0x1010:
        name: Store parameters
        category: optional
        get: node.od().getSave
        set: node.od().saveData
        data:
          - type: uint8
            name: highest sub-index supported
            access: ro
            default: 5
          - type: uint32
            name: save all parameters
            access: rw
          - type: uint32
            name: save communication parameters
            access: rw
          - type: uint32
            name: save application parameters
            access: rw
          - type: uint32
            name: save manufacturer specific parameters A
            access: rw
          - type: uint32
            name: save manufacturer specific parameters B
            access: rw
      0x1011:
        name: Restore default parameters
        category: optional
        data:
          - type: uint8
            name: highest sub-index supported
            access: ro
            default: 5
          - type: uint32
            name: restore all parameters
            access: rw
          - type: uint32
            name: restore communication parameters
            access: rw
          - type: uint32
            name: restore application parameters
            access: rw
          - type: uint32
            name: restore manufacturer specific parameters A
            access: rw
          - type: uint32
            name: restore manufacturer specific parameters B
            access: rw
      0x1018:
        name: Identity object
        category: mandatory
        data:
        - type: uint8
          name: Number of entries
          access: ro
          default: 4
        - type: uint32
          name: Vendor-ID
          access: ro
        - type: uint32
          name: Product code
          access: ro
        - type: uint32
          name: Revision number
          access: ro
        - type: uint32
          name: Serial number
          access: ro
      0x1019:
        name: Synchronous counter overflow value
        category: optional
        data:
        - type: uint8
          access: rw
      0x1400:
        name: Receive PDO 1 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 2
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000200
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
      0x1401:
        name: Receive PDO 2 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 2
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000300
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
      0x1402:
        name: Receive PDO 3 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 2
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000400
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
      0x1403:
        name: Receive PDO 4 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 2
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000500
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
      0x1600:
        name: Receive PDO 1 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1601:
        name: Receive PDO 2 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1602:
        name: Receive PDO 3 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1603:
        name: Receive PDO 4 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1800:
        name: Transmit PDO 1 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 6
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000180
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
        - type: uint16
          name: Inhibit time
          access: rw
        - type: uint8
          name: Compatibility entry
          access: rw
        - type: uint16
          name: Event timer
          access: rw
        - type: uint8
          name: Sync start value
          access: rw
      0x1801:
        name: Transmit PDO 2 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 6
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000280
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
        - type: uint16
          name: Inhibit time
          access: rw
        - type: uint8
          name: Compatibility entry
          access: rw
        - type: uint16
          name: Event timer
          access: rw
        - type: uint8
          name: Sync start value
          access: rw
      0x1802:
        name: Transmit PDO 3 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 6
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000380
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
        - type: uint16
          name: Inhibit time
          access: rw
        - type: uint8
          name: Compatibility entry
          access: rw
        - type: uint16
          name: Event timer
          access: rw
        - type: uint8
          name: Sync start value
          access: rw
      0x1803:
        name: Transmit PDO 4 communication parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: ro
          default: 6
        - type: uint32
          name: COB-ID
          default: $NODEID+0x80000480
          access: rw
        - type: uint8
          name: Transmission type
          access: rw
        - type: uint16
          name: Inhibit time
          access: rw
        - type: uint8
          name: Compatibility entry
          access: rw
        - type: uint16
          name: Event timer
          access: rw
        - type: uint8
          name: Sync start value
          access: rw
      0x1A00:
        name: Transmit PDO 1 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1A01:
        name: Transmit PDO 2 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1A02:
        name: Transmit PDO 3 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw
      0x1A03:
        name: Transmit PDO 4 mapping parameter
        category: optional
        data:
        - type: uint8
          name: Number of of entries
          access: rw
        - type: uint32
          name: 1st object to be mapped
          access: rw
        - type: uint32
          name: 2nd object to be mapped
          access: rw
        - type: uint32
          name: 3rd object to be mapped
          access: rw
        - type: uint32
          name: 4th object to be mapped
          access: rw
        - type: uint32
          name: 5th object to be mapped
          access: rw
        - type: uint32
          name: 6th object to be mapped
          access: rw
        - type: uint32
          name: 7th object to be mapped
          access: rw
        - type: uint32
          name: 8th object to be mapped
          access: rw

  402:
    name: Profile for drives and motion control
    objects:
      0x6040:
        name: Controlword
        category: mandatory
        data:
        - type: uint16
          access: rw
          pdo_mapping: true
          default: 0
      0x6041:
        name: Statusword
        category: mandatory
        data:
        - type: uint16
          access: ro
          pdo_mapping: true
          default: 0
      0x6060:
        name: Modes of operation
        data:
        - type: int8
          access: rw
          pdo_mapping: true
      0x6061:
        name: Modes of operation display
        data:
        - type: int8
          access: ro
          pdo_mapping: true
      0x6062:
        name: Position demand value
        data:
        - type: int32
          access: ro
          pdo_mapping: true
      0x6064:
        name: Position actual value
        data:
        - type: int32
          access: ro
          pdo_mapping: true
      0x606B:
        name: Velocity demand value
        data:
        - type: int32
          access: ro
          pdo_mapping: true
      0x606C:
        name: Velocity actual value
        data:
        - type: int32
          access: ro
          pdo_mapping: true
      0x6071:
        name: Target torque
        data:
        - type: int16
          access: rw
          pdo_mapping: true
      0x6075:
        name: motor rated current #TODO: add commissionning
        data:
        - type: uint32
          access: rw
      0x6076:
        name: motor rated torque 
        data:
        - type: uint32
          access: rw
      0x6077:
        name: Torque actual value
        data:
        - type: int16
          access: ro
          pdo_mapping: true
      0x6078:
        name: Current actual value
        data:
        - type: int16
          access: ro
          pdo_mapping: true
      0x607A:
        name: Target position
        data:
        - type: int32
          access: rw
          pdo_mapping: true
      0x6080:
        name: Max motor speed
        data:
        - type: uint32
          access: rw
      0x6081:
        name: Profile velocity
        data:
        - type: uint32
          access: rw
      0x6083:
        name: Profile acceleration
        data:
        - type: uint32
          access: rw
      0x6084:
        name: Profile deceleration
        data:
        - type: uint32
          access: rw
      0x608F:
        name: Position encoder resolution
        data:
        - type: uint8
          name: Highes sub-index supported
          access: ro
          default: 2
        - type: uint32 #TODO: remote get/set different
          name: Encoder increments
          access: rw
        - type: uint32
          name: motor revolutions
          access: rw
      0x60A8:
        name: SI unit Position
        data:
        - type: uint32
          access: rw
          default: 0xFD010000
      0x60A9:
        name: SI unit Velocity
        data:
        - type: uint32
          access: rw
          default: 0xFD010300
      0x60AA:
        name: SI unit Acceleration
        data:
        - type: uint32
          access: rw
          default: 0xFD015700
      0x60AB:
        name: SI unit Jerk
        data:
        - type: uint32
          access: rw
          default: 0xFD01A000
        
      