/**
 * Declaration of the EMCY class.
 */
#pragma once

#include <cstdint>

#include "enums.hpp"
#include "hal/can-transport.hpp"
#include "nmt/nmt.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"
#include "unions.hpp"

#define EMCY_DLC 8
#define EMCY_ERRCODE_OFFSET 0
#define EMCY_ERRREG_OFFSET 2
#define EMCY_MANUFACTURER_OFFSET 3
#define ERROR_REGISTER_INDEX 0x1001
#define PREDEFINED_ERROR_FIELD_SIZE 8
#define PREDEFINED_ERROR_FIELD_INDEX 0x1003
#define ERROR_BEHAVIOR_SIZE 2
#define ERROR_BEHAVIOR_INDEX 0x1029

namespace CANopen {
/**
 * Emergency object.
 * It handles the emission of emergency messages, as well as the pre-defined
 * error field and error register. See CiA301:2011§7.2.7 (p. 64)
 */

class ErrorRegister {
    int32_t odID;
    uint8_t value;

   public:
    ErrorRegister();
    void init(ObjectDictionnary &od);
    uint8_t getValue();
    void setErrorBit(unsigned bit);
    void clearErrorBit(unsigned bit);
    bool isErrorfree();
    void reset();
    int8_t getData(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t setData(const Data &data, int32_t id, SDOAbortCodes &abortCode);
};

class PreDefinesErrorField {
    int32_t odID;
    uint8_t errorsNumber;
    uint32_t errorsField[PREDEFINED_ERROR_FIELD_SIZE];

   public:
    void init(ObjectDictionnary &od);
    PreDefinesErrorField();
    void shiftErrors();
    void pushError(uint16_t errorCode, uint32_t manufacturerCode);
    void clearErrors();
    int8_t getData(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t setData(const Data &data, int32_t id, SDOAbortCodes &abortCode);
};

class ErrorBehavior {
    int32_t odID;
    uint8_t numberOfEntries;
    ErrorBehaviorValue communicationError;
    ErrorBehaviorValue internalDeviceError;

   public:
    void init(ObjectDictionnary &od);
    ErrorBehavior();
    ErrorBehaviorValue getCommunicationError();
    ErrorBehaviorValue getInternalDeviceError();
    int8_t getData(Data &data, int32_t id, SDOAbortCodes &abortCode);
    int8_t setData(const Data &data, int32_t id, SDOAbortCodes &abortCode);
};

class EMCY : public Service {
   public:
    ErrorRegister errorRegister;
    PreDefinesErrorField preDefinedErrorField;
    ErrorBehavior errorBehavior;

   private:
    /**
     * Internal method to send an error message.
     * @param errorCode The error code to send.
     * @param manufacturerCode The manufacturer-specific error code.
     */
    void sendError(uint16_t errorCode, uint32_t manufacturerCode);

    ObjectDictionnary &od;
    CanTransport &transport;
    NMT &nmt;
    const uint8_t nodeId;
    bool enabled = false;

   public:
    /**
     * Constructor for EMCY class.
     * @param od The object dictionary holding the error objects.
     * @param transport The transport the emergency frames are sent on.
     * @param nmt The state machine notified of the error behavior.
     * @param nodeId This node identifier.
     */
    EMCY(ObjectDictionnary &od, CanTransport &transport, NMT &nmt,
         uint8_t nodeId);

    void init() override;
    bool consumes(FunctionCodes) const override { return false; }
    void onFrame(class Frame &, uint32_t) override {}
    void update(uint32_t) override {}
    void onNmtState(NMTStates state) override;

    /**
     * Sends an emergency message on the bus, and automatically sets the
     * corresponding bits in the error register. The generic error bit is always
     * set when using this method.
     * @param errorCode The error code to send.
     * @param manufacturerCode The optional manufacturer-specific error code.
     */
    void raiseError(uint16_t errorCode, uint16_t manufacturerCode = 0);

    /**
     * Clear a specific error bit from the error register.
     * The generic error bit can only be cleared if all other bits are already
     * cleared.
     * @param bit The index of the error bit to clear.
     */
    void clearErrorBit(unsigned bit);
    void clearErrorBit(EMCYErrorCodes code);

    /**
     * Get the current error register value.
     * @return The error register value.
     */
    uint8_t getErrorRegister();

    /**
     * Clear the pre-defined error field (error history) in object 0x1003.
     */
    void clearHistory();

    /**
     * Completely reset the error register to 0.
     */
    void reset();
};
}  // namespace CANopen
