/**
 * Contains the declaration of the HB class.
 */
#pragma once

#include <cstdint>

#include "enums.hpp"
#include "hal/can-transport.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"
#include "unions.hpp"

#define HEARTBEAT_DLC 1
#define HEARTBEAT_STATE_OFFSET 0
#define TOGGLE_OFFSET 7
#define HEARTBEAT_INDEX 0x1017

namespace CANopen {

/**
 * Heartbeat object.
 * It automatically handles the following protocols: node guarding, heartbeat,
 * boot-up. See CiA301:2011§7.2.8.3.2.2 (p. 76)
 */
class HB : public Service {
   public:
    HB(ObjectDictionnary &od, CanTransport &transport, uint8_t nodeId);

    void init() override;
    bool consumes(FunctionCodes functionCode) const override {
        return functionCode == FunctionCode_HEARTBEAT;
    }

    /**
     * Receive and process a node guarding RTR frame.
     * @param frame Frame to be processed.
     * @param now_us Current timestamp in microseconds.
     */
    void onFrame(class Frame &frame, uint32_t now_us) override;

    /**
     * Publish the NMT state at the rate of the producer heartbeat time
     * (0x1017), when configured.
     * @param now_us Current timestamp in microseconds.
     */
    void update(uint32_t now_us) override;

    /**
     * Publish the boot-up message when leaving Initialisation, and follow the
     * state published by the heartbeat afterwards.
     * @param state The state the node just entered.
     */
    void onNmtState(NMTStates state) override;

    int8_t getData(Data &data, int32_t odID, SDOAbortCodes &abortCode);
    int8_t setData(const Data &data, int32_t odID, SDOAbortCodes &abortCode);

   private:
    /**
     * Internal method to publish the NMT state.
     * @param state NMT state to publish.
     * @param toggleBit Toggle bit value for node guarding (defaults to 0).
     */
    void publishState(NMTStates state, uint8_t toggleBit = 0);

    ObjectDictionnary &od;
    CanTransport &transport;
    const uint8_t nodeId;
    NMTStates state = NMTState_Initialisation;
    uint32_t lastPublish = 0;
    uint8_t toggleBit = 0;
    uint16_t heartbeatTime_ms = 0;
    int32_t odID = -1;
};
}  // namespace CANopen
