/**
 * Contains the declaration of the NMT class.
 */
#pragma once
#include <cstdint>

#include "enums.hpp"
#include "hal/remote-objects.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"

#define NMT_COMMAND_OFFSET 0
#define NMT_NODEID_OFFSET 1

namespace CANopen {

/**
 * NMT object.
 * It handles the reception of NMT commands, as well as the management of the
 * NMT state machine. See CiA301:2011§7.2.8 (p. 68)
 * Every state change is published to the services attached to the node.
 */
class NMT {
   private:
    ObjectDictionnary &od;
    RemoteObjects &remote;
    ServiceBus &bus;
    const uint8_t nodeId;
    NMTStates currentState = NMTState_Initialisation;
    NMTResetStates resetState = NMTResetState_Initialising;

    /**
     * Update the NMT state machine.
     * The state machine updating is event-driven, not periodic.
     * As such, this internal method is only called when a transition is issued
     * (besides initialization).
     * @param command NMT service command (default: None).
     */
    void updateSM(NMTServiceCommands command = NMTServiceCommand_None);

    /**
     * Run the Initialisation state: reload the dictionary, reset the remote
     * side and run the application hook.
     */
    void runInitialisation();

   public:
    NMT(ObjectDictionnary &od, RemoteObjects &remote, ServiceBus &bus,
        uint8_t nodeId);

    /** Application hook run after a reset node, once the remote side is reset.
     */
    void (*onReset)() = nullptr;

    /**
     * Initialize the NMT state machine.
     * Called by Node::init() to switch from Initialisation to Pre-Operational.
     */
    void initSM();

    /**
     * Receive and process an NMT frame.
     * Called by Node::receiveFrame().
     * @param frame NMTFrame to be processed.
     */
    void receiveFrame(class NMTFrame &frame);

    /**
     * Issue a state machine transition based on the given command.
     * @param command NMT service command.
     */
    void setTransition(NMTServiceCommands command);

    /**
     * Get the current state of the state machine.
     * @return The current NMT state.
     */
    NMTStates getState();
};
}  // namespace CANopen
