/**
 * Contains the declaration of the Node class.
 */
#pragma once

#include <cstdint>

#include "hal/can-transport.hpp"
#include "hal/persistence.hpp"
#include "hal/remote-objects.hpp"
#include "nmt/nmt.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "od/odAccessor.hpp"
#include "service.hpp"

namespace CANopen {

/**
 * Represents a CANopen slave node.
 * The node owns the object dictionary and the NMT state machine, and
 * dispatches frames and time to the services the application attached.
 */
class Node : public ServiceBus {
   private:
    ObjectDictionnary _od;
    ODAccessor _odAccessor;
    CanTransport &_transport;
    Persistence &_persistence;
    RemoteObjects &_remote;
    NMT _nmt;
    Service *_services[CANOPEN_MAX_SERVICES];
    uint8_t _serviceCount = 0;
    uint32_t timestamp_us = 0;

   public:
    const uint8_t nodeId = OD_NODE_ID;

    /**
     * Build a node on top of its hardware.
     * The application owns the three implementations and keeps them alive for
     * the whole life of the node.
     */
    Node(CanTransport &transport, Persistence &persistence,
         RemoteObjects &remote);

    /**
     * Attach a service to this node.
     * Services must be attached before init(), and outlive the node.
     * @param service The service to attach.
     * @return False if CANOPEN_MAX_SERVICES services are already attached.
     */
    bool attach(Service &service);

    /**
     * Get the Object Dictionnary object.
     * @return Reference to the ObjectDictionnary instance.
     */
    ObjectDictionnary &od();

    /**
     * Get the NMT object.
     * @return Reference to the NMT instance.
     */
    NMT &nmt();

    /**
     * Get the object dictionary accessor used by the SDO server.
     * Register a DomainHandler here to serve DOMAIN objects.
     * @return Reference to the ODAccessor instance.
     */
    ODAccessor &odAccessor();

    CanTransport &transport();
    Persistence &persistence();
    RemoteObjects &remote();

    /**
     * Initialize the hardware then the CANopen services.
     * This method will initialize the NMT state machine, so it should be called
     * when the node is ready to accept incoming frames.
     */
    void init();

    /**
     * Process a CANopen frame.
     * update() already drains the transport; call this only for frames coming
     * from another source.
     * @param frame The CANopen frame to process.
     */
    void receiveFrame(class Frame frame);

    /**
     * Drain the transport, poll the remote side and update the services.
     * This method should be called periodically.
     */
    void update();

    /**
     * Get the timestamp of the current update cycle in microseconds.
     * @return The current timestamp in microseconds.
     */
    uint32_t getTime_us();

    void publishNmtState(NMTStates state) override;
};
}  // namespace CANopen
