/**
 * Contains the declaration of the Node class.
 */
#pragma once

#include <cstdint>

#include "emergency.hpp"
#include "hal/can-transport.hpp"
#include "hal/persistence.hpp"
#include "hal/remote-objects.hpp"
#include "heartbeat.hpp"
#include "nmt.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "od/odAccessor.hpp"
#include "pdo.hpp"
#include "sdo/sdoServer.hpp"
#include "sync.hpp"

namespace CANopen {

/**
 * Represents a CANopen slave node.
 * This is the main class of this library.
 */
class Node {
   private:
    ObjectDictionnary _od;
    ODAccessor _odAccessor;
    NMT _nmt;
    HB _hb;
    SDO _sdo;
    PDO _pdo;
    SYNC _sync;
    EMCY _emcy;
    CanTransport &_transport;
    Persistence &_persistence;
    RemoteObjects &_remote;
    uint32_t timestamp_us = 0;

   public:
    friend NMT;
    friend HB;
    friend SDO;
    friend PDO;
    friend SYNC;
    friend EMCY;
    const uint8_t nodeId = OD_NODE_ID;

    /**
     * Build a node on top of its hardware.
     * The application owns the three implementations and keeps them alive for
     * the whole life of the node.
     */
    Node(CanTransport &transport, Persistence &persistence,
         RemoteObjects &remote);

    /**
     * Get the Object Dictionnary object.
     * @return Reference to the ObjectDictionnary instance.
     */
    ObjectDictionnary &od();

    /**
     * Get the NMT object.
     * @return Reference to the NMT instance.
     */
    NMT &nmt();

    /**
     * Get the Heartbeat object.
     * @return Reference to the HB instance.
     */
    HB &hb();

    /**
     * Get the object dictionary accessor used by the SDO server.
     * Register a DomainHandler here to serve DOMAIN objects.
     * @return Reference to the ODAccessor instance.
     */
    ODAccessor &odAccessor();

    /**
     * Get the SDO object.
     * @return Reference to the SDO instance.
     */
    SDO &sdo();

    /**
     * Get the PDO object.
     * @return Reference to the PDO instance.
     */
    PDO &pdo();

    /**
     * Get the Sync object.
     * @return Reference to the SYNC instance.
     */
    SYNC &sync();

    /**
     * Get the Emergency object.
     * @return Reference to the EMCY instance.
     */
    EMCY &emcy();

    CanTransport &transport();
    Persistence &persistence();
    RemoteObjects &remote();

    /**
     * Initialize the hardware then the CANopen services.
     * This method will initialize the NMT state machine, so it should be called
     * when the node is ready to accept incoming frames.
     */
    void init();

    /**
     * Process a CANopen frame.
     * update() already drains the transport; call this only for frames coming
     * from another source.
     * @param frame The CANopen frame to process.
     */
    void receiveFrame(class Frame frame);

    /**
     * Drain the transport, poll the remote side and update the services.
     * This method should be called periodically.
     */
    void update();

    /**
     * Get the timestamp of the current update cycle in microseconds.
     * @return The current timestamp in microseconds.
     */
    uint32_t getTime_us();
};
extern Node node;
}  // namespace CANopen
