/**
 * SYNC consumer.
 *
 * The SYNC producer broadcasts the synchronization object periodically.
 * This SYNC provides the basic network synchronization mechanism.
 * The time period between the SYNCs is specified by the standard
 * parameter communication cycle period.
 */
#pragma once

#include <cstdint>
#include <functional>

#include "enums.hpp"
#include "od.hpp"  // Generated by the Object Dictionnary generator
#include "service.hpp"
#include "unions.hpp"

#define SYNC_COUNTER_OFFSET 0
#define SYNC_INDEX 0x1019
#define NO_COUNTER 0
#define MIN_COUNTER 2
#define MAX_COUNTER 240

namespace CANopen {

class PDO;

/**
 * SYNC object.
 * It automatically handles the reception of SYNC events and calls associated
 * callback for PDO class. See CiA301:2011§7.2.5 (p. 62)
 */
class SYNC : public Service {
   public:
    /**
     * Constructor for the SYNC class.
     * @param od The object dictionary holding 0x1019.
     * @param pdo The PDO service to synchronize, null when the node has none.
     */
    SYNC(ObjectDictionnary &od, PDO *pdo = nullptr);

    void init() override;
    bool consumes(FunctionCodes functionCode) const override {
        return functionCode == FunctionCode_SYNC;
    }

    /**
     * Receive and process a SYNC frame.
     * This method receives and processes a SYNC frame, updating internal state
     * and performing actions as needed.
     * @param frame SYNCFrame to be processed.
     * @param now_us Timestamp in microseconds of the frame reception.
     */
    void onFrame(class Frame &frame, uint32_t now_us) override;

    void update(uint32_t now_us) override;
    void onNmtState(NMTStates state) override;

    /**
     * Set a callback function to be called when a SYNC message is received.
     * The function will receive the counter value.
     * This callback is called before any PDO action.
     * **DO NOT use time consuming calls in the provided callback.**
     * @param callback Callback function to be called on SYNC event.
     */
    void onSync(std::function<void(unsigned)> callback);

    int8_t getData(Data &data, int32_t odID, SDOAbortCodes &abortCode);
    int8_t setData(const Data &data, int32_t odID, SDOAbortCodes &abortCode);

   private:
    ObjectDictionnary &od;
    PDO *pdo;
    int32_t odID = -1;
    bool enabled = false;
    uint8_t internalCounter = 1;
    uint8_t maxCounter = MAX_COUNTER;
    std::function<void(unsigned)> onSyncFunc;
};
}  // namespace CANopen
